### ISSUE TITLE
List View cant scroll up

### ISSUE THREAD

**Issue by JoelAH** [bradmartin/nativescript-pulltorefresh#36] opened 2017-11-19 19:57 UTC
Scrolling the list view is ok, but when I am trying to scroll back up to the top, The refresher comes up. Trying to scroll back up is being interpreted as a refresh command. The refresher should come up when i reach the top, and then pull down.

**Comment by bradmartin** [comment] 2017-11-19 23:11
This might be an issue with your layout, can you paste the snippet? If that's not it then something has broken recently, not necessarily the plugin source but core modules, android lib, etc. Will know more if I can see the layout you're using.

**Comment by JoelAH** [comment] 2017-11-20 01:15
Hi. Well this is the layout im using:

<PullRefresh:PullToRefresh refresh="refreshList">
<GridLayout  rows="auto,*" class="page-content" loaded="onLoaded">
                
        <ListView row="1" class="listview list-top" items="{{items}}">
            <ListView.itemTemplate>
                <GridLayout>
                    <Label col="0" style="margin-right:98%;background-color:green;width:2%;" class="{{progress}}" text=" "  />
                    <Label col="1" class="time" text="{{time}}"/>
                    <StackLayout col="2">
                        <Label class="fn" text="{{fname}}"/>
                        <Label class="ln" text="{{lname}}"/>
                        
                    </StackLayout>
                    <StackLayout col="3">
                        <Label  class="phone" text="{{phone}}"/>
                    </StackLayout>
                    
                    
                </GridLayout>
            </ListView.itemTemplate>
        </ListView>
</GridLayout>
</PullRefresh:PullToRefresh>

This view is in a tab view.

**Comment by JoelAH** [comment] 2017-11-20 01:18
This is the layout I use. It is inside a TabViewItem:

`<PullRefresh:PullToRefresh refresh="refreshList">
<GridLayout  rows="auto,*" class="page-content" loaded="onLoaded">
        <ListView row="1" class="listview list-top" items="{{items}}">
            <ListView.itemTemplate>
                <GridLayout>
                    <Label col="0" style="margin-right:98%;background-color:green;width:2%;" class="{{progress}}" text=" "  />
                    <Label col="1" class="time" text="{{time}}"/>
                    <StackLayout col="2">
                        <Label class="fn" text="{{fname}}"/>
                        <Label class="ln" text="{{lname}}"/>
                    </StackLayout>
                    <StackLayout col="3">
                        <Label  class="phone" text="{{phone}}"/>
                    </StackLayout>
                </GridLayout>
            </ListView.itemTemplate>
        </ListView>
</GridLayout>
</PullRefresh:PullToRefresh> `

**Comment by JoelAH** [comment] 2017-11-20 01:19
`If I put the PullRefresh inside the top GridLayout, the screen will be blank

**Comment by JoelAH** [comment] 2017-11-22 01:23
Any word on this?

**Comment by JoelAH** [comment] 2017-11-25 04:30
Any word?

**Comment by bradmartin** [comment] 2017-11-25 21:43
I think you need to put the PullToRefresh in your grid, the reason you say `screen will be blank` is likely that you aren't assigning it a row in the grid and/or you don't have height/width for the component to know how to fill the parent. On Android this isn't as big of an issue as it is on iOS where iOS layouts don't automatically `fill` their parent layouts by design.

I have updated the demo app today and it works fine, so the issue is your layout. If you need any further help, the slack channel or NS forums seem most appropriate right now. Thanks 😄

**Closed by bradmartin** 2017-11-25 21:43 UTC
